In [65]:
%pip install tensorflow nltk gensim

Requirement already satisfied: tensorflow in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (2.21.0)
Requirement already satisfied: nltk in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (3.9.4)
Requirement already satisfied: gensim in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (4.4.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: setuptools in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (57.4.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.2.6)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.33.1)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\velicia\appdata\roaming\python\python310\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: packaging in c:\users\velicia\appdata\roaming\python\python310\site-packages (from tensorflow) (26.0)
Requirement already satisfied: six>=1.12.0 in c:\users\velicia\appdata\roaming\python\python310\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: joblib in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: click in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.3.3)
Requirement already satisfied: tqdm in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: scipy>=1.7.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from gensim) (7.6.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: optree in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: rich in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: colorama in c:\users\velicia\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\velicia\appdata\roaming\python\python310\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\velicia\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.1.1 is available.
You should consider upgrading via the 'c:\Users\Velicia\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [66]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow.keras import Sequential, callbacks, layers, optimizers, Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import joblib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler
import re
import nltk
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Velicia\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Velicia\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [67]:
cv_df = pd.read_csv('cv_processed.csv')
job_df = pd.read_csv('JobMarket_Preprocessed.csv')

In [68]:
cv_df.head()

,Unnamed: 0,user_id,raw_cv_text,extracted_user_skills,last_role,education,major,extracted_skills_structured,projects,experience
0,0,1,one97 communication limited data scientist jan...,object detection market research natural langu...,data scientist jan 2019 to till date,probability estimate premium amount charged bt...,"computer science, engineering, data science","python, java, machine learning, deep learning,...",expand arsenal application building work diffe...,limited data scientist jan 2019 till date | co...
1,1,2,attila lászló joó phd external advisor phd civ...,virtual design independent research and develo...,phd civil engineer,attila lászló joó phd external advisor phd civ...,"engineering, civil engineering","analysis, model, engineering, design",bridge numerical modelling steel joint virtual...,phd civil engineer present workplace assistant...
2,2,3,vineet mathradas way 3023 house 1918 po box 60...,business reporting revenue kingdom company mai...,vineet\tmathradas\t\tway\tno\t3023\thouse\tno\...,2017 london school economics political science...,"business, finance, economics","analysis, model",comprehensive financial model comprising annua...,class india senior school examination grade 12...
3,3,4,ákos pohl chief executive manager msc civil en...,marital status design cleaning msc optimal sol...,civil engineer ceos civil engineering optimal...,email apohlce oseu qualification msc diploma c...,"engineering, civil engineering, economics","excel, engineering, design",isd dunaferr project 2008 hexagon team award 2...,chief executive manager msc civil engineering ...
4,4,5,resume name rama krushna dash post applied mec...,medical marital status notification pneumatic ...,post applied for ...,berhampur odisha 71 recently completed btech ...,"engineering, mechanical engineering","engineering, design",located centrally project site ii preventive m...,applied mechanical engineer contact 9078684961...

In [69]:
job_df.head()

,job_id,job_title,extracted_job_skills,experienced_level,extracted_job_skills_count,role_category,extracted_requirements,extracted_responsibilities
0,1,data analyst,sql,entry level,1,data analyst,s1 teknik industri informatika sains fresh gra...,menarik data dari database dan menyajikan seca...
1,2,data analyst/intelligence,power bi tableau excel,mid level,3,data analyst,bachelors degree in finance accounting economi...,build maintain and automate dashboards daily w...
2,3,data analyst,spss sql python power bi oracle excel,unspecified,6,other,data analyst 1 mengerti bahasa pemrograman bah...,data analyst berikut merupakan job desk data a...
3,4,data analyst associate,sql tableau python power bi oracle,senior level,5,data analyst,craft sql scripts examine source data structur...,get to know the team you will join a dynamic t...
4,5,data analyst officer for finance divison,excel,mid level,1,data analyst,bachelors degree any discipline with preferenc...,supporting accounting division in preparing th...

### Tokenize

In [70]:
cv_skills = cv_df['extracted_skills_structured'].tolist()
job_skills = job_df['extracted_job_skills'].tolist()
all_skills = cv_skills + job_skills
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(all_skills)

In [71]:
MAX_SEQUENCE_LENGTH = 256

def encode(text):
    sequences = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')
    return padded[0]

cv_df['encoded_skills'] = cv_df['extracted_skills_structured'].apply(encode)
job_df['encoded_skills'] = job_df['extracted_job_skills'].apply(encode)

### Model

In [72]:
x_cv = np.array(cv_df['encoded_skills'].tolist())
x_job = np.array(job_df['encoded_skills'].tolist())
x = np.vstack([x_cv, x_job])
y = np.array([1] * len(x_cv) + [0] * len(x_job))

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

In [73]:
embedding_dim = 300
vocab_size = 10000

inp = layers.Input(shape=(None,), dtype="int32")
x = layers.Embedding(vocab_size, embedding_dim, mask_zero=True)(inp)
x = layers.Bidirectional(layers.LSTM(128, return_sequences=True))(x)
x = layers.Bidirectional(layers.LSTM(64))(x)
x = layers.Dense(64, activation='relu')(x)
x = layers.Dropout(0.2)(x)
x = layers.Dense(1, activation='sigmoid')(x)
model = Model(inp, x, name="skillscout_nusantara")

In [74]:
callbacks_custom = [
    EarlyStopping(
        monitor='val_loss',
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=3,
        min_lr=1e-7,
        verbose=1
    ),
]

In [75]:
model.compile(
    loss='binary_crossentropy', 
    optimizer=optimizers.Adam(learning_rate=0.01), 
    metrics=['accuracy']
)

In [76]:
history = model.fit(
    x_train, y_train,
    validation_data=(x_val, y_val),
    epochs=50,
    batch_size=32,
    callbacks=callbacks_custom,
    verbose=1
)

Epoch 1/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 411ms/step - accuracy: 0.9793 - loss: 0.0666 - val_accuracy: 1.0000 - val_loss: 0.0034 - learning_rate: 0.0100
Epoch 2/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 392ms/step - accuracy: 0.9992 - loss: 0.0067 - val_accuracy: 1.0000 - val_loss: 4.6397e-05 - learning_rate: 0.0100
Epoch 3/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 383ms/step - accuracy: 1.0000 - loss: 1.2971e-04 - val_accuracy: 1.0000 - val_loss: 5.9317e-06 - learning_rate: 0.0100
Epoch 4/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 393ms/step - accuracy: 1.0000 - loss: 4.4451e-05 - val_accuracy: 1.0000 - val_loss: 2.0715e-06 - learning_rate: 0.0100
Epoch 5/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step - accuracy: 1.0000 - loss: 8.0640e-06
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.004999999888241291.
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 399ms/step - accuracy: 1.0000 - loss: 1.5480e-05 - val_accuracy: 1.0000 - val_loss: 1.5081e-06 - learning_rate: 0.0100
Epoch 6/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 389ms/step - accuracy: 1.0000 - loss: 1.0820e-04 - val_accuracy: 1.0000 - val_loss: 7.0682e-07 - learning_rate: 0.0050
Epoch 7/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 405ms/step - accuracy: 1.0000 - loss: 1.2710e-05 - val_accuracy: 1.0000 - val_loss: 5.8685e-07 - learning_rate: 0.0050
Epoch 8/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - accuracy: 1.0000 - loss: 1.1643e-06
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0024999999441206455.
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 377ms/step - accuracy: 1.0000 - loss: 1.6244e-06 - val_accuracy: 1.0000 - val_loss: 5.4988e-07 - learning_rate: 0.0050
Epoch 9/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 359ms/step - accuracy: 1.0000 - loss: 3.7664e-06 - val_accuracy: 1.0000 - val_loss: 5.2584e-07 - learning_rate: 0.0025
Epoch 10/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - accuracy: 1.0000 - loss: 1.1116e-04 - val_accuracy: 1.0000 - val_loss: 3.9323e-07 - learning_rate: 0.0025
Epoch 11/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - accuracy: 1.0000 - loss: 3.0021e-06
Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0012499999720603228.
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 356ms/step - accuracy: 1.0000 - loss: 1.6523e-06 - val_accuracy: 1.0000 - val_loss: 3.6862e-07 - learning_rate: 0.0025
Epoch 12/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 367ms/step - accuracy: 1.0000 - loss: 2.7688e-05 - val_accuracy: 1.0000 - val_loss: 3.3274e-07 - learning_rate: 0.0012
Epoch 13/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 371ms/step - accuracy: 1.0000 - loss: 1.6087e-04 - val_accuracy: 1.0000 - val_loss: 2.8129e-07 - learning_rate: 0.0012
Epoch 14/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step - accuracy: 1.0000 - loss: 1.8370e-05
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0006249999860301614.
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 365ms/step - accuracy: 1.0000 - loss: 1.4938e-05 - val_accuracy: 1.0000 - val_loss: 2.2589e-07 - learning_rate: 0.0012
Epoch 15/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 355ms/step - accuracy: 1.0000 - loss: 1.8079e-05 - val_accuracy: 1.0000 - val_loss: 2.1690e-07 - learning_rate: 6.2500e-04
Epoch 16/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 358ms/step - accuracy: 1.0000 - loss: 3.6665e-06 - val_accuracy: 1.0000 - val_loss: 2.1288e-07 - learning_rate: 6.2500e-04
Epoch 17/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step - accuracy: 1.0000 - loss: 1.0516e-05
Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0003124999930150807.
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 375ms/step - accuracy: 1.0000 - loss: 8.8371e-06 - val_accuracy: 1.0000 - val_loss: 2.0849e-07 - learning_rate: 6.2500e-04
Epoch 18/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - accuracy: 1.0000 - loss: 7.7351e-05 - val_accuracy: 1.0000 - val_loss: 2.0144e-07 - learning_rate: 3.1250e-04
Epoch 19/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 358ms/step - accuracy: 1.0000 - loss: 2.6628e-06 - val_accuracy: 1.0000 - val_loss: 1.9661e-07 - learning_rate: 3.1250e-04
Epoch 20/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - accuracy: 1.0000 - loss: 2.2984e-05
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.00015624999650754035.
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 365ms/step - accuracy: 1.0000 - loss: 1.1315e-05 - val_accuracy: 1.0000 - val_loss: 1.9346e-07 - learning_rate: 3.1250e-04
Epoch 21/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 364ms/step - accuracy: 1.0000 - loss: 2.9479e-05 - val_accuracy: 1.0000 - val_loss: 1.9044e-07 - learning_rate: 1.5625e-04
Epoch 22/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 360ms/step - accuracy: 1.0000 - loss: 1.8283e-06 - val_accuracy: 1.0000 - val_loss: 1.8946e-07 - learning_rate: 1.5625e-04
Epoch 23/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 367ms/step - accuracy: 1.0000 - loss: 2.6837e-05
Epoch 23: ReduceLROnPlateau reducing learning rate to 7.812499825377017e-05.
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 391ms/step - accuracy: 1.0000 - loss: 1.4819e-05 - val_accuracy: 1.0000 - val_loss: 1.8711e-07 - learning_rate: 1.5625e-04
Epoch 24/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 376ms/step - accuracy: 1.0000 - loss: 2.0421e-06 - val_accuracy: 1.0000 - val_loss: 1.8672e-07 - learning_rate: 7.8125e-05
Epoch 25/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 375ms/step - accuracy: 1.0000 - loss: 1.9643e-05 - val_accuracy: 1.0000 - val_loss: 1.8613e-07 - learning_rate: 7.8125e-05
Epoch 26/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - accuracy: 1.0000 - loss: 4.2346e-06
Epoch 26: ReduceLROnPlateau reducing learning rate to 3.9062499126885086e-05.
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 361ms/step - accuracy: 1.0000 - loss: 4.7591e-05 - val_accuracy: 1.0000 - val_loss: 1.8457e-07 - learning_rate: 7.8125e-05
Epoch 27/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - accuracy: 1.0000 - loss: 6.1319e-06 - val_accuracy: 1.0000 - val_loss: 1.8350e-07 - learning_rate: 3.9062e-05
Epoch 28/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 518ms/step - accuracy: 1.0000 - loss: 2.4366e-05 - val_accuracy: 1.0000 - val_loss: 1.8278e-07 - learning_rate: 3.9062e-05
Epoch 29/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step - accuracy: 1.0000 - loss: 6.3828e-06
Epoch 29: ReduceLROnPlateau reducing learning rate to 1.9531249563442543e-05.
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 515ms/step - accuracy: 1.0000 - loss: 4.3919e-06 - val_accuracy: 1.0000 - val_loss: 1.8234e-07 - learning_rate: 3.9062e-05
Epoch 30/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 512ms/step - accuracy: 1.0000 - loss: 2.7659e-06 - val_accuracy: 1.0000 - val_loss: 1.8224e-07 - learning_rate: 1.9531e-05
Epoch 31/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 468ms/step - accuracy: 1.0000 - loss: 9.1954e-05 - val_accuracy: 1.0000 - val_loss: 1.8151e-07 - learning_rate: 1.9531e-05
Epoch 32/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 434ms/step - accuracy: 1.0000 - loss: 4.4763e-06
Epoch 32: ReduceLROnPlateau reducing learning rate to 9.765624781721272e-06.
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 460ms/step - accuracy: 1.0000 - loss: 4.7904e-06 - val_accuracy: 1.0000 - val_loss: 1.8127e-07 - learning_rate: 1.9531e-05
Epoch 33/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 457ms/step - accuracy: 1.0000 - loss: 5.3227e-05 - val_accuracy: 1.0000 - val_loss: 1.8103e-07 - learning_rate: 9.7656e-06
Epoch 34/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 469ms/step - accuracy: 1.0000 - loss: 4.0390e-06 - val_accuracy: 1.0000 - val_loss: 1.8095e-07 - learning_rate: 9.7656e-06
Epoch 35/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 450ms/step - accuracy: 1.0000 - loss: 1.6488e-04
Epoch 35: ReduceLROnPlateau reducing learning rate to 4.882812390860636e-06.
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 477ms/step - accuracy: 1.0000 - loss: 8.3940e-05 - val_accuracy: 1.0000 - val_loss: 1.8055e-07 - learning_rate: 9.7656e-06
Epoch 36/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 462ms/step - accuracy: 1.0000 - loss: 6.5034e-06 - val_accuracy: 1.0000 - val_loss: 1.8049e-07 - learning_rate: 4.8828e-06
Epoch 37/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 476ms/step - accuracy: 1.0000 - loss: 2.8534e-05 - val_accuracy: 1.0000 - val_loss: 1.8036e-07 - learning_rate: 4.8828e-06
Epoch 38/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 437ms/step - accuracy: 1.0000 - loss: 4.5388e-06
Epoch 38: ReduceLROnPlateau reducing learning rate to 2.441406195430318e-06.
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 465ms/step - accuracy: 1.0000 - loss: 3.1117e-06 - val_accuracy: 1.0000 - val_loss: 1.8029e-07 - learning_rate: 4.8828e-06
Epoch 39/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 472ms/step - accuracy: 1.0000 - loss: 5.5458e-06 - val_accuracy: 1.0000 - val_loss: 1.8025e-07 - learning_rate: 2.4414e-06
Epoch 40/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 377ms/step - accuracy: 1.0000 - loss: 7.4549e-05 - val_accuracy: 1.0000 - val_loss: 1.8018e-07 - learning_rate: 2.4414e-06
Epoch 41/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - accuracy: 1.0000 - loss: 2.2028e-06
Epoch 41: ReduceLROnPlateau reducing learning rate to 1.220703097715159e-06.
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 361ms/step - accuracy: 1.0000 - loss: 2.4982e-06 - val_accuracy: 1.0000 - val_loss: 1.8010e-07 - learning_rate: 2.4414e-06
Epoch 42/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 358ms/step - accuracy: 1.0000 - loss: 7.2524e-06 - val_accuracy: 1.0000 - val_loss: 1.8009e-07 - learning_rate: 1.2207e-06
Epoch 43/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 353ms/step - accuracy: 1.0000 - loss: 3.6086e-05 - val_accuracy: 1.0000 - val_loss: 1.8004e-07 - learning_rate: 1.2207e-06
Epoch 44/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - accuracy: 1.0000 - loss: 3.5183e-06
Epoch 44: ReduceLROnPlateau reducing learning rate to 6.103515488575795e-07.
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 368ms/step - accuracy: 1.0000 - loss: 1.6084e-06 - val_accuracy: 1.0000 - val_loss: 1.8004e-07 - learning_rate: 1.2207e-06
Epoch 45/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 360ms/step - accuracy: 1.0000 - loss: 9.6030e-06 - val_accuracy: 1.0000 - val_loss: 1.8003e-07 - learning_rate: 6.1035e-07
Epoch 46/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 359ms/step - accuracy: 1.0000 - loss: 1.2479e-05 - val_accuracy: 1.0000 - val_loss: 1.8002e-07 - learning_rate: 6.1035e-07
Epoch 47/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 419ms/step - accuracy: 1.0000 - loss: 1.1869e-05
Epoch 47: ReduceLROnPlateau reducing learning rate to 3.0517577442878974e-07.
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 458ms/step - accuracy: 1.0000 - loss: 1.0174e-05 - val_accuracy: 1.0000 - val_loss: 1.8001e-07 - learning_rate: 6.1035e-07
Epoch 48/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 497ms/step - accuracy: 1.0000 - loss: 8.9005e-06 - val_accuracy: 1.0000 - val_loss: 1.8001e-07 - learning_rate: 3.0518e-07
Epoch 49/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 473ms/step - accuracy: 1.0000 - loss: 2.4218e-05 - val_accuracy: 1.0000 - val_loss: 1.8000e-07 - learning_rate: 3.0518e-07
Epoch 50/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 436ms/step - accuracy: 1.0000 - loss: 1.0214e-05
Epoch 50: ReduceLROnPlateau reducing learning rate to 1.5258788721439487e-07.
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 465ms/step - accuracy: 1.0000 - loss: 1.9559e-05 - val_accuracy: 1.0000 - val_loss: 1.7999e-07 - learning_rate: 3.0518e-07
Restoring model weights from the end of the best epoch: 50.

In [89]:
from sklearn.metrics.pairwise import cosine_similarity

# Ambil sample CV dan Job skills
cv_skills = cv_df['encoded_skills'].iloc[0]  # CV pertama
job_skills = job_df['encoded_skills'].iloc[10]  # Job pertama

# Hitung similarity dengan cosine
similarity = cosine_similarity([cv_skills], [job_skills])[0][0]
similarity_percentage = similarity * 100

print(f"Similarity Score: {similarity_percentage:.2f}%")
job_skills = job_df.iloc[10]
job_skills

Similarity Score: 45.06%

job_id                                                                       11
job_title                                                   junior data analyst
extracted_job_skills                        sql tableau python r power bi excel
experienced_level                                                   unspecified
extracted_job_skills_count                                                    6
role_category                                                      data analyst
extracted_requirements        bachelors degree in data science statistics co...
extracted_responsibilities    as the data analyst at bnc you will play a cru...
encoded_skills                [8, 11, 12, 13, 9, 10, 3, 0, 0, 0, 0, 0, 0, 0,...
Name: 10, dtype: object

In [86]:
cv1 = cv_df.iloc[0]
cv1

Unnamed: 0                                                                     0
user_id                                                                        1
raw_cv_text                    one97 communication limited data scientist jan...
extracted_user_skills          object detection market research natural langu...
last_role                                   data scientist jan 2019 to till date
education                      probability estimate premium amount charged bt...
major                                computer science, engineering, data science
extracted_skills_structured    python, java, machine learning, deep learning,...
projects                       expand arsenal application building work diffe...
experience                     limited data scientist jan 2019 till date | co...
encoded_skills                 [12, 20, 49, 38, 50, 38, 51, 52, 16, 64, 16, 2...
Name: 0, dtype: object