In [1]:
%pip install tensorflow nltk gensim PySastrawi

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: PySastrawi in /usr/local/lib/python3.12/dist-packages (1.2.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, mean_absolute_error, roc_auc_score
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import Sequential, callbacks, layers, optimizers, Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import joblib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler
import re
import nltk
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
from sklearn.metrics.pairwise import cosine_similarity
import keras
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
cv_df = pd.read_csv('cv_processed.csv')
job_df = pd.read_csv('JobMarket_Preprocessed.csv')

In [4]:
cv_df.head()

,Unnamed: 0,user_id,name,last_role,raw_cv_text,extracted_user_skills,education,major,extracted_skills_structured,projects,experience
0,0,4053a618-a3ad-48a8-bc47-60f2b78f23a9,Rian Setiawan,ui designer magang,curriculum vitae ringkas nama rian setiawan ko...,"figma, user research, ui ux, prototyping, krea...",not specified,other,"figma, user research, ui ux, prototyping, krea...",not specified,not specified
1,1,6cbc999b-c041-4015-bf6f-dea1ec3249c4,Fikran Setiawan,ketua bem,curriculum vitae ringkas nama fikran setiawan ...,"leadership, microsoft office, manajemen waktu,...",not specified,other,"leadership, microsoft office, manajemen waktu,...",not specified,terapkan meliputi leadership microsoft office ...
2,2,e52de38f-bf7b-4567-9217-78bf54964452,Rina Siregar,asisten laboratorium komputer,curriculum vitae ringkas nama rina siregar kon...,"postgresql, problem solving, html css",not specified,other,"postgresql, problem solving, html css",not specified,not specified
3,3,6cdd63df-d646-4127-ba00-8c5fc8ce7097,Sri Setiawan,content creator,curriculum vitae ringkas nama sri setiawan kon...,"figma, adobe illustrator, prototyping",not specified,other,"figma, adobe illustrator, prototyping",not specified,not specified
4,4,dd0c1320-a40d-41da-8c52-31fda2009b20,Eko Utomo,sales executive,curriculum vitae ringkas nama eko utomo kontak...,"manajemen waktu, komunikasi, agile, negosiasi,...",not specified,other,"manajemen waktu, komunikasi, agile, negosiasi,...",not specified,not specified

In [5]:
job_df.head()

,job_id,job_title,extracted_skills,experience_level,extracted_job_skills_count,role_category,extracted_requirements,extracted_responsibilities
0,dcedd22a-ecbf-402c-b657-570885b37fb3,it recruiter,"scrum, problem solving, strategic planning, ag...",senior level,5,hr / recruiter,teknis wajib menguasai scrum problem solving s...,NaN
1,302bcf5b-303e-4501-9b38-7b0eda40366a,data analyst,"scikit-learn, data visualization, scrum, agile...",NaN,5,data analyst,teknis wajib menguasai scikitlearn data visual...,NaN
2,fb99ecb9-f527-4116-aea8-89c9b86cf1f7,product manager,"scrum, leadership, strategic planning, agile, ...",NaN,5,product manager,teknis wajib menguasai scrum leadership strate...,NaN
3,1e1524a0-81bb-4bbe-bf56-e33c2747683d,devops engineer,"javascript, fastapi, typescript, scrum, strate...",entry level,7,devops / cloud engineer,teknis wajib menguasai javascript fastapi type...,NaN
4,7b388edf-df9d-40d3-9dbf-9da15eb0bba1,ui/ux designer,"ui/ux, komunikasi, design system, wireframing,...",NaN,6,ux / ui designer,teknis wajib menguasai uiux komunikasi design ...,NaN

### Tokenize

In [6]:
NORMALIZE = {
      'power bi': 'powerbi',
      'machine learning': 'machinelearning',
      'deep learning': 'deeplearning',
      'natural language processing': 'nlp',
      'data analysis': 'dataanalysis',
      'data analytics': 'dataanalytics',
      'data science': 'datascience',
      'data engineering': 'dataengineering',
      'computer vision': 'computervision',
      'neural network': 'neuralnetwork',
      'big data': 'bigdata',
      'project management': 'projectmanagement',
      'time series': 'timeseries',
      'scikit learn': 'scikitlearn',
      'google analytics': 'googleanalytics',
      'looker studio': 'lookerstudio',
  }

def normalize_skills(text):
      t = str(text).lower()
      for phrase, token in NORMALIZE.items():
          t = t.replace(phrase, token)
      return t

In [7]:
cv_df['extracted_skills_structured'] = cv_df['extracted_skills_structured'].apply(normalize_skills)
job_df['extracted_skills'] = job_df['extracted_skills'].apply(normalize_skills)

In [8]:
cv_skills = cv_df['extracted_skills_structured'].fillna('').tolist()
job_skills = job_df['extracted_skills'].fillna('').tolist()
all_skills = cv_skills + job_skills
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(all_skills)

In [9]:
joblib.dump(tokenizer, 'tokenizer.joblib')

['tokenizer.joblib']

In [10]:
MAX_SEQUENCE_LENGTH = 256

def encode(text):
    sequences = tokenizer.texts_to_sequences(text)
    padded = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')
    return padded

x_cv = encode(cv_df['extracted_skills_structured'].fillna('').tolist())
x_job = encode(job_df['extracted_skills'].fillna('').tolist())

print("x_cv shape :", x_cv.shape)
print("x_job shape:", x_job.shape)

x_cv shape : (501, 256)
x_job shape: (501, 256)

In [11]:
def jaccard(text_a, text_b):
    a = set(s.strip() for s in str(text_a).split(',') if s.strip())
    b = set(s.strip() for s in str(text_b).split(',') if s.strip())

    if not a and not b:
        return 0.0
    return len(a & b) / len(a | b)

cv_pairs, job_pairs, labels = [], [], []
positive_pairs = []
negative_pairs = []

for cv_i in range(len(cv_df)):
    for job_i in range(len(job_df)):
        score = jaccard(
            cv_df['extracted_skills_structured'].iloc[cv_i],
            job_df['extracted_skills'].iloc[job_i]
        )
        if score > 0:
            positive_pairs.append((cv_i, job_i, score))
        else:
            negative_pairs.append((cv_i, job_i, score))

n = min(len(positive_pairs), len(negative_pairs))
selected = positive_pairs[:n] + negative_pairs[:n]
random.shuffle(selected)

for cv_i, job_i, score in selected:
    cv_pairs.append(x_cv[cv_i])
    job_pairs.append(x_job[job_i])
    labels.append(score)

labels = np.array(labels)

print(f"Total pairs: {len(labels)}")
print(f"Sum of Jaccard Scores: {labels.sum():.4f}")
print(f"Count of 0 Jaccard Scores: {(labels==0).sum()}")

Total pairs: 188784
Sum of Jaccard Scores: 15094.9236
Count of 0 Jaccard Scores: 94392

### Model

In [12]:
EMBEDDING_DIM = 300
VOCAB_SIZE = 10000

def build_encoder(vocab_size, embedding_dim, max_sequence_length):
    inp = layers.Input(shape=(None,), dtype="int32")
    x = layers.Embedding(vocab_size, embedding_dim, mask_zero=True)(inp)
    x = layers.Bidirectional(layers.LSTM(128, return_sequences=True))(x)
    x = layers.Bidirectional(layers.LSTM(64))(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.2)(x)
    x = layers.Lambda(lambda v: v / (tf.norm(v, axis=1, keepdims=True) + 1e-8), name='l2_normalize')(x)
    model = Model(inp, x, name='skillscout_nusantara')
    return model

def build_siamese(vocab_size, embedding_dim, max_len):
    encoder = build_encoder(vocab_size, embedding_dim, max_len)
    inp_cv  = layers.Input(shape=(max_len,), name='cv_input')
    inp_job = layers.Input(shape=(max_len,), name='job_input')
    emb_cv  = encoder(inp_cv)
    emb_job = encoder(inp_job)

    similarity = layers.Dot(axes=1, normalize=False, name='cosine')([emb_cv, emb_job])
    siamese = Model([inp_cv, inp_job], similarity, name='siamese_bilstm')
    return siamese, encoder

siamese, encoder = build_siamese(VOCAB_SIZE, EMBEDDING_DIM, MAX_SEQUENCE_LENGTH)
siamese.summary()

Model: "siamese_bilstm"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ cv_input            │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ job_input           │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ skillscout_nusanta… │ (None, 64)        │  3,611,904 │ cv_input[0][0],   │
│ (Functional)        │                   │            │ job_input[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cosine (Dot)        │ (None, 1)         │          0 │ skillscout_nusan… │
│                     │                   │            │ skillscout_nusan… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_15 (Dense)    │ (None, 1)         │          2 │ cosine[0][0]      │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 3,611,906 (13.78 MB)

 Trainable params: 3,611,906 (13.78 MB)

 Non-trainable params: 0 (0.00 B)

In [13]:
from sklearn.model_selection import train_test_split

cv_tr, cv_val, job_tr, job_val, y_tr, y_val = train_test_split(
    cv_pairs, job_pairs, labels,
    test_size=0.2, random_state=42
)

In [14]:
epochs = 20
batch_size = 64
optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001)
loss_fn = tf.keras.losses.MeanSquaredError()

train_loss = tf.keras.metrics.Mean(name='train_loss')
train_mae = tf.keras.metrics.MeanAbsoluteError(name='train_mae')
val_loss = tf.keras.metrics.Mean(name='val_loss')
val_mae = tf.keras.metrics.MeanAbsoluteError(name='val_mae')

train_ds = tf.data.Dataset.from_tensor_slices((cv_tr, job_tr, y_tr)).shuffle(10000).batch(batch_size)
val_ds = tf.data.Dataset.from_tensor_slices((cv_val, job_val, y_val)).batch(batch_size)

In [15]:
@tf.function
def train_step(cv, job, labels):
    with tf.GradientTape() as tape:
        predictions = siamese([cv, job], training=True)
        loss = loss_fn(labels, predictions)

    gradients = tape.gradient(loss, siamese.trainable_variables)
    optimizer.apply_gradients(zip(gradients, siamese.trainable_variables))

    train_loss(loss)
    train_mae(labels, predictions)

@tf.function
def val_step(cv, job, labels):
    predictions = siamese([cv, job], training=False)
    loss = loss_fn(labels, predictions)

    val_loss(loss)
    val_mae(labels, predictions)

In [16]:
history = {'train_loss': [], 'train_mae': [], 'val_loss': [], 'val_mae': []}

best_val_loss = float('inf')
patience = 0

for epoch in range(1, epochs + 1):
  train_loss.reset_state()
  train_mae.reset_state()
  val_loss.reset_state()
  val_mae.reset_state()

  for cv_batch, job_batch, label_batch in train_ds:
    train_step(cv_batch, job_batch, label_batch)

  for cv_batch, job_batch, label_batch in val_ds:
    val_step(cv_batch, job_batch, label_batch)

  res_train_loss = train_loss.result().numpy()
  res_train_mae = train_mae.result().numpy()
  res_val_loss = val_loss.result().numpy()
  res_val_mae = val_mae.result().numpy()

  history['train_loss'].append(res_train_loss)
  history['train_mae'].append(res_train_mae)
  history['val_loss'].append(res_val_loss)
  history['val_mae'].append(res_val_mae)

  print(f"Epoch {epoch}/{epochs}  loss: {res_train_loss:.4f}  mae: {res_train_mae:.4f}  val_loss: {res_val_loss:.4f}  val_mae: {res_val_mae:.4f}")

  # early stopping
  if res_val_loss < best_val_loss:
    best_val_loss = res_val_loss
    patience = 0
    siamese.save('best_model.keras')
  else:
    patience += 1
    if patience >= 5:
      print("Early stopping aktif")
      break

  # ReduceLROnPletaeu
  current_lr = float(optimizer.learning_rate)
  if patience == 5 or current_lr < 1e-6:
    new_lr = current_lr * 0.5
    optimizer.learning_rate.assign(new_lr)
    print(f"Mengurangi learning rate menjadi {new_lr}")
    patience = 0

Epoch 1/20  loss: 0.0028  mae: 0.0332  val_loss: 0.0017  val_mae: 0.0253
Epoch 2/20  loss: 0.0019  mae: 0.0264  val_loss: 0.0011  val_mae: 0.0206
Epoch 3/20  loss: 0.0018  mae: 0.0255  val_loss: 0.0011  val_mae: 0.0222
Epoch 4/20  loss: 0.0017  mae: 0.0244  val_loss: 0.0007  val_mae: 0.0165
Epoch 5/20  loss: 0.0016  mae: 0.0237  val_loss: 0.0008  val_mae: 0.0190
Epoch 6/20  loss: 0.0016  mae: 0.0235  val_loss: 0.0008  val_mae: 0.0172
Epoch 7/20  loss: 0.0015  mae: 0.0229  val_loss: 0.0009  val_mae: 0.0185
Epoch 8/20  loss: 0.0015  mae: 0.0227  val_loss: 0.0008  val_mae: 0.0175
Epoch 9/20  loss: 0.0015  mae: 0.0226  val_loss: 0.0007  val_mae: 0.0169
Early stopping aktif

In [17]:
cv_embedded = encoder.predict(x_cv, verbose=0)
job_embedded = encoder.predict(x_job, verbose=0)

### Accuracy and MAE

In [18]:
cv_val_array = np.array(cv_val)
job_val_array = np.array(job_val)

pred_val = siamese.predict([cv_val_array, job_val_array], verbose=0).flatten()
val_mae = mean_absolute_error(y_val, pred_val)
print(f"MAE on Validation Set: {val_mae:.4f}")

np.random.seed(42)
N = 500
pool_size = 2000
cv_pool  = np.random.randint(0, len(cv_df),  pool_size)
job_pool = np.random.randint(0, len(job_df), pool_size)

pool_scores = np.array([
    jaccard(cv_df['extracted_skills_structured'].iloc[ci],
            job_df['extracted_skills'].iloc[ji])
    for ci, ji in zip(cv_pool, job_pool)
])

pos_idx = np.where(pool_scores > 0)[0]
neg_idx = np.where(pool_scores == 0)[0]

n_each = N // 2
pos_idx = pos_idx[:n_each]
neg_idx = neg_idx[:n_each]
selected = np.concatenate([pos_idx, neg_idx])

cv_idx_list  = cv_pool[selected]
job_idx_list = job_pool[selected]
true_scores  = pool_scores[selected]

print(f"Distribusi label: Positif: {(true_scores > 0).sum()}, Negatif: {(true_scores == 0).sum()}")

pred_scores = siamese.predict([x_cv[cv_idx_list], x_job[job_idx_list]], verbose=0).flatten()

mae = mean_absolute_error(true_scores, pred_scores)
print(f"MAE (regresi): {mae:.4f}") # target maksimal 0.02

binary_true_for_pool = (true_scores > 0).astype(int)

THRESHOLD = 0.5
binary_true_for_val = (y_val > 0).astype(int)
binary_pred = (pred_val >= THRESHOLD).astype(int)

print(f"Accuracy: {accuracy_score(binary_true_for_val, binary_pred)*100:.2f}%")
print(f"F1-Score: {f1_score(binary_true_for_val, binary_pred):.4f}")
print(f"ROC-AUC: {roc_auc_score(binary_true_for_val, pred_val):.4f}")
print(f"Classfication Report:")
print(classification_report(binary_true_for_val, binary_pred))

MAE on Validation Set: 0.0169
Distribusi label: Positif: 250, Negatif: 250
MAE (regresi): 0.0170
Accuracy: 50.55%
F1-Score: 0.0191
ROC-AUC: 0.9997
Classfication Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67     18906
           1       1.00      0.01      0.02     18851

    accuracy                           0.51     37757
   macro avg       0.75      0.50      0.34     37757
weighted avg       0.75      0.51      0.34     37757

### Matching CV ke Job

In [19]:
def parse_cv_skills(text):
    skills = set(s.strip().lower() for s in str(text).replace('/', ',').split(',') if s.strip())
    tokens = set(word for skill in skills for word in skill.split())
    return skills | tokens

def parse_job_skills(text):
    return set(s.strip().lower() for s in str(text).split(',') if s.strip() and len(s.strip()) > 1)

def match_cv_to_jobs(cv_idx, top_k=20):
    cv_emb  = cv_embedded[cv_idx].reshape(1, -1)
    scores  = cosine_similarity(cv_emb, job_embedded)[0]
    top_idx = np.argsort(scores)[::-1][:top_k]

    cv_skills_raw = parse_cv_skills(cv_df['extracted_user_skills'].iloc[cv_idx])

    results = []

    for job_idx in top_idx:
        job_row = job_df.iloc[job_idx]

        job_skills_raw = parse_job_skills(job_df['extracted_skills'].iloc[job_idx])

        matched_skills = job_skills_raw & cv_skills_raw
        gap_skills     = job_skills_raw - cv_skills_raw

        results.append({
            'job_title'      : job_row['job_title'],
            'matching_score' : f"{scores[job_idx]*100:.2f}%",
            'matched_skills' : sorted(matched_skills),
            'skill_gap'      : sorted(gap_skills),
        })

    return results

In [20]:
matches = match_cv_to_jobs(cv_idx=0, top_k=20)
for m in matches:
    print(f"\n{m['job_title']} — Skor: {m['matching_score']}")
    print(f"  Skill Cocok : {m['matched_skills']}")
    print(f"  Skill Kurang: {m['skill_gap']}")

ui/ux designer — Skor: 40.81%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'leadership', 'photoshop', 'projectmanagement']

ui/ux designer — Skor: 37.61%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'agile', 'design system', 'wireframing']

ui/ux designer — Skor: 36.56%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'design system', 'projectmanagement', 'wireframing']

ui/ux designer — Skor: 36.41%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'leadership', 'strategic planning', 'wireframing']

ui/ux designer — Skor: 36.26%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'agile', 'design system', 'ui/ux']

ui/ux designer — Skor: 33.22%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'komunikasi', 'projectmanagement', 'ui/ux', 'wireframing']

ui/ux designer — Skor: 32.77%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'design system', 'jira', 'projectmanagement', 'ui/ux']

ui/ux designer — Skor: 29.82%
  Skill Cocok : ['prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'design system', 'photoshop', 'strategic planning']

ui/ux designer — Skor: 29.29%
  Skill Cocok : ['prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'design system', 'jira', 'photoshop']

ui/ux designer — Skor: 28.69%
  Skill Cocok : ['prototyping', 'user research']
  Skill Kurang: ['adobe illustrator', 'scrum', 'ui/ux', 'wireframing']

ui/ux designer — Skor: 27.25%
  Skill Cocok : ['figma', 'user research']
  Skill Kurang: ['adobe illustrator', 'design system', 'leadership', 'photoshop', 'wireframing']

ui/ux designer — Skor: 26.59%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['leadership', 'ui/ux', 'wireframing']

ui/ux designer — Skor: 26.32%
  Skill Cocok : ['figma', 'user research']
  Skill Kurang: ['adobe illustrator', 'design system', 'problem solving', 'ui/ux', 'wireframing']

ui/ux designer — Skor: 26.06%
  Skill Cocok : ['figma', 'user research']
  Skill Kurang: ['adobe illustrator', 'agile', 'design system', 'komunikasi', 'photoshop']

ui/ux designer — Skor: 25.99%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['design system', 'photoshop', 'problem solving', 'ui/ux']

ui/ux designer — Skor: 23.62%
  Skill Cocok : ['figma', 'prototyping', 'user research']
  Skill Kurang: ['design system', 'jira', 'photoshop', 'scrum', 'wireframing']

ui/ux designer — Skor: 22.87%
  Skill Cocok : ['figma', 'user research']
  Skill Kurang: ['adobe illustrator', 'design system', 'komunikasi', 'ui/ux', 'wireframing']

ui/ux designer — Skor: 21.85%
  Skill Cocok : ['prototyping']
  Skill Kurang: ['adobe illustrator', 'negosiasi', 'photoshop', 'strategic planning']

ui/ux designer — Skor: 21.07%
  Skill Cocok : ['prototyping', 'user research']
  Skill Kurang: ['problem solving', 'ui/ux', 'wireframing']

ui/ux designer — Skor: 20.53%
  Skill Cocok : ['figma', 'prototyping']
  Skill Kurang: ['design system', 'jira', 'wireframing']