In [105]:
%pip install tensorflow nltk gensim PySastrawi

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: PySastrawi in /usr/local/lib/python3.12/dist-packages (1.2.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [106]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow.keras import Sequential, callbacks, layers, optimizers, Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import joblib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler
import re
import nltk
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
from sklearn.metrics.pairwise import cosine_similarity
import keras
from sklearn.metrics import mean_absolute_error, accuracy_score
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [107]:
cv_df = pd.read_csv('cv_processed.csv')
job_df = pd.read_csv('JobMarket_Preprocessed.csv')

In [108]:
cv_df.head()

,Unnamed: 0,user_id,raw_cv_text,extracted_user_skills,last_role,education,major,extracted_skills_structured,projects,experience
0,0,1,one97 communication limited data scientist jan...,object detection market research natural langu...,data scientist jan 2019 to till date,probability estimate premium amount charged bt...,"computer science, engineering, data science","python, java, r, machine learning, deep learni...",expand arsenal application building work diffe...,limited data scientist jan 2019 till date | co...
1,1,2,attila lászló joó phd external advisor phd civ...,virtual design independent research and develo...,phd civil engineer,attila lászló joó phd external advisor phd civ...,"engineering, civil engineering",r,bridge numerical modelling steel joint virtual...,phd civil engineer present workplace assistant...
2,2,3,vineet mathradas way 3023 house 1918 po box 60...,business reporting revenue kingdom company mai...,vineet\tmathradas\t\tway\tno\t3023\thouse\tno\...,2017 london school economics political science...,"business, finance, economics",r,comprehensive financial model comprising annua...,class india senior school examination grade 12...
3,3,4,ákos pohl chief executive manager msc civil en...,marital status design cleaning msc optimal sol...,civil engineer ceos civil engineering optimal...,email apohlce oseu qualification msc diploma c...,"engineering, civil engineering, economics","r, excel",isd dunaferr project 2008 hexagon team award 2...,chief executive manager msc civil engineering ...
4,4,5,resume name rama krushna dash post applied mec...,medical marital status notification pneumatic ...,post applied for ...,berhampur odisha 71 recently completed btech ...,"engineering, mechanical engineering",r,located centrally project site ii preventive m...,applied mechanical engineer contact 9078684961...

In [109]:
job_df.head()

,job_id,job_title,extracted_job_skills,experienced_level,extracted_job_skills_count,role_category,extracted_requirements,extracted_responsibilities
0,1,data analyst,sql,entry level,1,data analyst,s1 teknik industri informatika sains fresh gra...,menarik data dari database dan menyajikan seca...
1,2,data analyst/intelligence,power bi tableau excel,mid level,3,data analyst,bachelors degree in finance accounting economi...,build maintain and automate dashboards daily w...
2,3,data analyst,spss sql python power bi oracle excel,unspecified,6,other,data analyst 1 mengerti bahasa pemrograman bah...,data analyst berikut merupakan job desk data a...
3,4,data analyst associate,sql tableau python power bi oracle,senior level,5,data analyst,craft sql scripts examine source data structur...,get to know the team you will join a dynamic t...
4,5,data analyst officer for finance divison,excel,mid level,1,data analyst,bachelors degree any discipline with preferenc...,supporting accounting division in preparing th...

### Tokenize

In [110]:
cv_skills = cv_df['extracted_skills_structured'].tolist()
job_skills = job_df['extracted_job_skills'].tolist()
all_skills = cv_skills + job_skills
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(all_skills)

In [111]:
MAX_SEQUENCE_LENGTH = 256

def encode(text):
    sequences = tokenizer.texts_to_sequences(text)
    padded = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')
    return padded

x_cv = encode(cv_df['extracted_skills_structured'].tolist())
x_job = encode(job_df['extracted_job_skills'].tolist())

print("x_cv shape :", x_cv.shape)
print("x_job shape:", x_job.shape)

x_cv shape : (18, 256)
x_job shape: (1612, 256)

In [112]:
def jaccard(text_a, text_b):
    a = set(s.strip().lower() for s in str(text_a).replace('/', ',').split(',') if s.strip())
    b = set(s.strip().lower() for s in str(text_b).replace('/', ',').split(',') if s.strip())
    if not a and not b:
        return 0.0
    return len(a & b) / len(a | b)

cv_pairs, job_pairs, labels = [], [], []

for cv_i in range(len(cv_df)):
    for job_i in range(len(job_df)):
        score = jaccard(
            cv_df['extracted_skills_structured'].iloc[cv_i],
            job_df['extracted_job_skills'].iloc[job_i]
        )
        cv_pairs.append(x_cv[cv_i])
        job_pairs.append(x_job[job_i])
        labels.append(score)  # Store actual Jaccard score instead of binary label

cv_pairs  = np.array(cv_pairs)
job_pairs = np.array(job_pairs)
labels    = np.array(labels)

print(f"Total pairs: {len(labels)}")
print(f"Sum of Jaccard Scores: {labels.sum():.4f}")
print(f"Count of 0 Jaccard Scores: {(labels==0).sum()}")

Total pairs: 29016
Sum of Jaccard Scores: 164.1037
Count of 0 Jaccard Scores: 28550

### Model

In [113]:
EMBEDDING_DIM = 300
VOCAB_SIZE = 10000

def build_encoder(vocab_size, embedding_dim, max_sequence_length):
    inp = layers.Input(shape=(None,), dtype="int32")
    x = layers.Embedding(vocab_size, embedding_dim, mask_zero=True)(inp)
    x = layers.Bidirectional(layers.LSTM(128, return_sequences=True))(x)
    x = layers.Bidirectional(layers.LSTM(64))(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.2)(x)
    x = layers.Lambda(lambda v: v / (tf.norm(v, axis=1, keepdims=True) + 1e-8), name='l2_normalize')(x)
    model = Model(inp, x, name='skillscout_nusantara')
    return model

def build_siamese(vocab_size, embedding_dim, max_len):
    encoder = build_encoder(vocab_size, embedding_dim, max_len)
    inp_cv  = layers.Input(shape=(max_len,), name='cv_input')
    inp_job = layers.Input(shape=(max_len,), name='job_input')
    emb_cv  = encoder(inp_cv)
    emb_job = encoder(inp_job)

    similarity = layers.Dot(axes=1, normalize=False, name='cosine')([emb_cv, emb_job])
    output     = layers.Dense(1, activation='sigmoid')(similarity)
    siamese = Model([inp_cv, inp_job], output, name='siamese_bilstm')
    return siamese, encoder

siamese, encoder = build_siamese(VOCAB_SIZE, EMBEDDING_DIM, MAX_SEQUENCE_LENGTH)
siamese.summary()

Model: "siamese_bilstm"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ cv_input            │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ job_input           │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ skillscout_nusanta… │ (None, 64)        │  3,611,904 │ cv_input[0][0],   │
│ (Functional)        │                   │            │ job_input[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cosine (Dot)        │ (None, 1)         │          0 │ skillscout_nusan… │
│                     │                   │            │ skillscout_nusan… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_15 (Dense)    │ (None, 1)         │          2 │ cosine[0][0]      │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 3,611,906 (13.78 MB)

 Trainable params: 3,611,906 (13.78 MB)

 Non-trainable params: 0 (0.00 B)

In [114]:
from sklearn.model_selection import train_test_split

cv_tr, cv_val, job_tr, job_val, y_tr, y_val = train_test_split(
    cv_pairs, job_pairs, labels,
    test_size=0.2, random_state=42
)

In [115]:
epochs = 20
batch_size = 64
optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01)
loss_fn = tf.keras.losses.MeanSquaredError()

train_loss = tf.keras.metrics.Mean(name='train_loss')
train_mae = tf.keras.metrics.MeanAbsoluteError(name='train_mae')
val_loss = tf.keras.metrics.Mean(name='val_loss')
val_mae = tf.keras.metrics.MeanAbsoluteError(name='val_mae')

train_ds = tf.data.Dataset.from_tensor_slices((cv_tr, job_tr, y_tr)).shuffle(10000).batch(batch_size)
val_ds = tf.data.Dataset.from_tensor_slices((cv_val, job_val, y_val)).batch(batch_size)

In [116]:
@tf.function
def train_step(cv, job, labels):
    with tf.GradientTape() as tape:
        predictions = siamese([cv, job], training=True)
        loss = loss_fn(labels, predictions)

    gradients = tape.gradient(loss, siamese.trainable_variables)
    optimizer.apply_gradients(zip(gradients, siamese.trainable_variables))

    train_loss(loss)
    train_mae(labels, predictions)

@tf.function
def val_step(cv, job, labels):
    predictions = siamese([cv, job], training=False)
    loss = loss_fn(labels, predictions)

    val_loss(loss)
    val_mae(labels, predictions)

In [117]:
history = {'train_loss': [], 'train_mae': [], 'val_loss': [], 'val_mae': []}

best_val_loss = float('inf')
patience = 0

for epoch in range(1, epochs + 1):
  train_loss.reset_state()
  train_mae.reset_state()
  val_loss.reset_state()
  val_mae.reset_state()

  for cv_batch, job_batch, label_batch in train_ds:
    train_step(cv_batch, job_batch, label_batch)

  for cv_batch, job_batch, label_batch in val_ds:
    val_step(cv_batch, job_batch, label_batch)

  res_train_loss = train_loss.result().numpy()
  res_train_mae = train_mae.result().numpy()
  res_val_loss = val_loss.result().numpy()
  res_val_mae = val_mae.result().numpy()

  history['train_loss'].append(res_train_loss)
  history['train_mae'].append(res_train_mae)
  history['val_loss'].append(res_val_loss)
  history['val_mae'].append(res_val_mae)

  print(f"Epoch {epoch}/{epochs}  loss: {res_train_loss:.4f}  mae: {res_train_mae:.4f}  val_loss: {res_val_loss:.4f}  val_mae: {res_val_mae:.4f}")

  # early stopping
  if res_val_loss < best_val_loss:
    best_val_loss = res_val_loss
    patience = 0
    siamese.save('best_model.keras')
  else:
    patience += 1
    if patience >= 5:
      print("Early stopping aktif")
      break

  # ReduceLROnPletaeu
  current_lr = float(optimizer.learning_rate)
  if patience == 3 or current_lr < 1e-6:
    new_lr = current_lr * 0.5
    optimizer.learning_rate.assign(new_lr)
    print(f"Mengurangi learning rate menjadi {new_lr}")
    patience = 0

Epoch 1/20  loss: 0.0180  mae: 0.1125  val_loss: 0.0029  val_mae: 0.0371
Epoch 2/20  loss: 0.0035  mae: 0.0424  val_loss: 0.0023  val_mae: 0.0229
Epoch 3/20  loss: 0.0028  mae: 0.0302  val_loss: 0.0022  val_mae: 0.0177
Epoch 4/20  loss: 0.0026  mae: 0.0245  val_loss: 0.0022  val_mae: 0.0150
Epoch 5/20  loss: 0.0025  mae: 0.0212  val_loss: 0.0022  val_mae: 0.0133
Epoch 6/20  loss: 0.0025  mae: 0.0188  val_loss: 0.0022  val_mae: 0.0121
Epoch 7/20  loss: 0.0024  mae: 0.0173  val_loss: 0.0022  val_mae: 0.0112
Epoch 8/20  loss: 0.0024  mae: 0.0160  val_loss: 0.0022  val_mae: 0.0105
Epoch 9/20  loss: 0.0024  mae: 0.0149  val_loss: 0.0022  val_mae: 0.0100
Mengurangi learning rate menjadi 0.004999999888241291
Epoch 10/20  loss: 0.0024  mae: 0.0143  val_loss: 0.0022  val_mae: 0.0098
Epoch 11/20  loss: 0.0024  mae: 0.0139  val_loss: 0.0022  val_mae: 0.0096
Epoch 12/20  loss: 0.0024  mae: 0.0136  val_loss: 0.0022  val_mae: 0.0094
Mengurangi learning rate menjadi 0.0024999999441206455
Epoch 13/20  loss: 0.0024  mae: 0.0133  val_loss: 0.0022  val_mae: 0.0093
Epoch 14/20  loss: 0.0024  mae: 0.0131  val_loss: 0.0022  val_mae: 0.0092
Epoch 15/20  loss: 0.0024  mae: 0.0129  val_loss: 0.0022  val_mae: 0.0090
Mengurangi learning rate menjadi 0.0012499999720603228
Epoch 16/20  loss: 0.0024  mae: 0.0128  val_loss: 0.0022  val_mae: 0.0090
Epoch 17/20  loss: 0.0024  mae: 0.0126  val_loss: 0.0022  val_mae: 0.0089
Epoch 18/20  loss: 0.0024  mae: 0.0125  val_loss: 0.0022  val_mae: 0.0089
Mengurangi learning rate menjadi 0.0006249999860301614
Epoch 19/20  loss: 0.0024  mae: 0.0124  val_loss: 0.0022  val_mae: 0.0088
Epoch 20/20  loss: 0.0024  mae: 0.0124  val_loss: 0.0022  val_mae: 0.0088

In [118]:
cv_embedded = encoder.predict(x_cv, verbose=0)
job_embedded = encoder.predict(x_job, verbose=0)

### Accuracy and MAE

In [119]:
pred_val = siamese.predict([cv_val, job_val], verbose=0).flatten()
val_mae = mean_absolute_error(y_val, pred_val)
print(f"MAE on Validation Set: {val_mae:.4f}")

np.random.seed(42)
N = 500
cv_idx_list  = np.random.randint(0, len(cv_df),  N)
job_idx_list = np.random.randint(0, len(job_df), N)

true_scores = []

for cv_i, job_i in zip(cv_idx_list, job_idx_list):
    # Ground truth = Jaccard
    true_scores.append(jaccard(
        cv_df['extracted_skills_structured'].iloc[cv_i],
        job_df['extracted_job_skills'].iloc[job_i]
    ))

true_scores = np.array(true_scores)

pred_scores = siamese.predict([x_cv[cv_idx_list], x_job[job_idx_list]], verbose=0).flatten()

mae = mean_absolute_error(true_scores, pred_scores)
print(f"MAE      : {mae:.4f}") # target maksimal 0.02

binary_true_labels = (true_scores > 0).astype(int)

best_accuracy = 0
optimal_threshold = 0

thresholds = np.linspace(0, 1, 100)

for threshold in thresholds:
    binary_pred_labels = (pred_scores >= threshold).astype(int)
    current_accuracy = accuracy_score(binary_true_labels, binary_pred_labels)
    if current_accuracy > best_accuracy:
        best_accuracy = current_accuracy
        optimal_threshold = threshold

print(f"Optimal Threshold for Accuracy: {optimal_threshold:.4f}")
print(f"Best Accuracy with Optimal Threshold: {best_accuracy:.4f} ({best_accuracy*100:.2f}%)") # target minimal 85%

MAE on Validation Set: 0.0088
MAE      : 0.0074
Optimal Threshold for Accuracy: 0.0101
Best Accuracy with Optimal Threshold: 0.9920 (99.20%)

### Matching CV ke Job

In [120]:
def parse_cv_skills(text):
    skills = set(s.strip().lower() for s in str(text).replace('/', ',').split(',') if s.strip())
    tokens = set(word for skill in skills for word in skill.split())
    return skills | tokens

def parse_job_skills(text):
    return set(s.strip().lower() for s in str(text).split() if s.strip() and len(s.strip()) > 1)

def match_cv_to_jobs(cv_idx, top_k=20):
    cv_emb  = cv_embedded[cv_idx].reshape(1, -1)
    scores  = cosine_similarity(cv_emb, job_embedded)[0]
    top_idx = np.argsort(scores)[::-1][:top_k]

    cv_skills_raw = parse_cv_skills(cv_df['extracted_skills_structured'].iloc[cv_idx])

    results = []

    for job_idx in top_idx:
        job_row = job_df.iloc[job_idx]

        job_skills_raw = parse_job_skills(job_df['extracted_job_skills'].iloc[job_idx])

        matched_skills = job_skills_raw & cv_skills_raw
        gap_skills     = job_skills_raw - cv_skills_raw

        results.append({
            'job_title'      : job_row['job_title'],
            'matching_score' : f"{scores[job_idx]*100:.2f}%",
            'matched_skills' : sorted(matched_skills),
            'skill_gap'      : sorted(gap_skills),
        })

    return results

In [121]:
matches = match_cv_to_jobs(cv_idx=0, top_k=20)
for m in matches:
    print(f"\n{m['job_title']} — Skor: {m['matching_score']}")
    print(f"  Skill Cocok : {m['matched_skills']}")
    print(f"  Skill Kurang: {m['skill_gap']}")

senior performance marketing & analyst — Skor: 100.00%
  Skill Cocok : ['data']
  Skill Kurang: ['analytics', 'google', 'looker', 'studio']

finance solutions excellence analyst — Skor: 100.00%
  Skill Cocok : ['python']
  Skill Kurang: ['aws', 'azure', 'cloud', 'google', 'sql']

data analyst — Skor: 100.00%
  Skill Cocok : ['data', 'python']
  Skill Kurang: ['airflow', 'aws', 'azure', 'bi', 'bigquery', 'cloud', 'excel', 'gcp', 'google', 'looker', 'matplotlib', 'mysql', 'numpy', 'pandas', 'postgresql', 'power', 'seaborn', 'snowflake', 'sql', 'studio', 'tableau', 'talend']

web developer - data analyst - tele marketing - head marketing — Skor: 100.00%
  Skill Cocok : ['data', 'python']
  Skill Kurang: ['excel', 'google', 'javascript', 'sql', 'studio', 'tableau']

data analyst staff — Skor: 100.00%
  Skill Cocok : ['python']
  Skill Kurang: ['excel', 'mysql']

data engineer (analyst, etl, dba) — Skor: 100.00%
  Skill Cocok : ['python']
  Skill Kurang: ['bi', 'oracle', 'power', 'server', 'sql', 'ssis', 'tableau']

technical business analyst — Skor: 100.00%
  Skill Cocok : []
  Skill Kurang: ['aws', 'azure', 'excel']

junior financial modeling analyst — Skor: 100.00%
  Skill Cocok : ['python']
  Skill Kurang: ['excel', 'javascript', 'sql']

data analyst associate — Skor: 100.00%
  Skill Cocok : ['python']
  Skill Kurang: ['bi', 'oracle', 'power', 'sql', 'tableau']

senior business analyst — Skor: 100.00%
  Skill Cocok : []
  Skill Kurang: ['bigquery', 'segment', 'sql']

senior data analyst — Skor: 100.00%
  Skill Cocok : ['data', 'python']
  Skill Kurang: ['google', 'metabase', 'sql', 'studio', 'tableau']

digital marketing analyst — Skor: 100.00%
  Skill Cocok : []
  Skill Kurang: ['analytics', 'google', 'tableau']

senior risk analyst - kyc & ato — Skor: 100.00%
  Skill Cocok : []
  Skill Kurang: ['bigquery', 'looker', 'metabase']

business analyst (data analyst) — Skor: 100.00%
  Skill Cocok : []
  Skill Kurang: ['excel', 'looker', 'sql', 'tableau']

marketing analyst | tdo jakarta — Skor: 100.00%
  Skill Cocok : []
  Skill Kurang: ['analytics', 'google', 'tableau']

analytics & data engineer lead — Skor: 100.00%
  Skill Cocok : ['java', 'python']
  Skill Kurang: ['analytics', 'api', 'google', 'metabase', 'sql']

(senior) syslog server analyst — Skor: 100.00%
  Skill Cocok : ['java', 'python']
  Skill Kurang: ['aws', 'azure', 'sql']

product analyst — Skor: 100.00%
  Skill Cocok : ['python']
  Skill Kurang: ['aws', 'azure', 'bi', 'gcp', 'looker', 'power', 'sql', 'tableau']

data analyst — Skor: 100.00%
  Skill Cocok : ['data', 'python']
  Skill Kurang: ['aws', 'azure', 'bi', 'gcp', 'google', 'power', 'sql', 'studio', 'tableau']

junior business analyst — Skor: 100.00%
  Skill Cocok : ['python']
  Skill Kurang: ['excel', 'sql', 'tableau']